version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@bamdadsabbagh/eslint-config"
    versions:
    - 1.7.1
    - 1.8.0
    - 1.8.1
    - 1.8.3
    - 1.8.4
    - 1.8.5
    - 1.8.6
    - 1.9.1
    - 1.9.2
    - 1.9.3
    - 1.9.4
    - 1.9.6
  - dependency-name: "@bamdadsabbagh/stylelint-config"
    versions:
    - 1.3.0
